# Default values for convoy-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  port: 5005
  resources:
    limits:
      cpu: 50m
      memory: 60Mi
    requests:
      cpu: 40m
      memory: 50Mi
env:
  auth:
    jwt:
      enabled: true
    native:
      enabled: true
  log_level: "debug"
  environment: ""
  host: ""
  search:
    enabled: false
    type: ""
    api_key: ""
    host: ""
  smtp:
    enabled: false
    from: ""
    password: ""
    port: 0
    provider: ""
    url: ""
    username: ""
  tracer:
    enabled: false
    app_name: ""
    config_enabled: false
    distributed_tracer_enabled: false
    license_key: ""
    type: ""

image:
  repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
  pullPolicy: Always
  tag: v23.05.3

nameOverride: "convoy-server"
fullNameOverride: "convoy-server"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
