{{- if .Values.podDisruptionBudget -}}
{{- if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "convoy-server.fullname" . }}
  labels:
    {{- include "convoy-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "convoy-server.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end -}}