# Default values for convoy worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  port: 5006
  resources:
    limits:
      cpu: 50m
      memory: 60Mi
    requests:
      cpu: 40m
      memory: 50Mi

env:
  proxy: ""
  log_level: "debug"

image:
  repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
  pullPolicy: Always
  tag: v23.05.3

nameOverride: "convoy-worker"
fullNameOverride: "convoy-worker"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
